In [20]:
from extract_map import extract_map

from l5kit.configs import load_config_data
from l5kit.data import ChunkedDataset, LocalDataManager, MapAPI
from l5kit.dataset import EgoDataset, AgentDataset
from l5kit.geometry import transform_points
from l5kit.rasterization import build_rasterizer
from l5kit.rasterization.rasterizer_builder import _load_metadata

import numpy as np

import os

In [21]:
os.environ["L5KIT_DATA_FOLDER"] = "/Users/nicole/OSU/l5kit/prediction-dataset"

cfg = load_config_data("/Users/nicole/OSU/l5kit/examples/visualisation/visualisation_config.yaml")

In [22]:
dm = LocalDataManager()
dataset_path = dm.require(cfg["val_data_loader"]["key"])
zarr_dataset = ChunkedDataset(dataset_path)
zarr_dataset.open()

rast = build_rasterizer(cfg, dm)
# train_dataset = AgentDataset(cfg, zarr_dataset, rast)
train_dataset = EgoDataset(cfg, zarr_dataset, rast)

In [23]:
semantic_map_filepath = dm.require(cfg['raster_params']['semantic_map_key'])

dataset_meta = _load_metadata('/Users/nicole/OSU/l5kit/prediction-dataset/semantic_map/' + 
                              cfg['raster_params']['dataset_meta_key'], 
                              dm)
world_to_ecef = np.array(dataset_meta["world_to_ecef"], dtype=np.float64)

map_api = MapAPI(semantic_map_filepath, world_to_ecef)
lane_bounds = map_api.bounds_info["lanes"]["bounds"]

In [24]:
lane_bounds[0]


array([[  883.0814253 , -1550.10978153],
       [  959.24549828, -1500.92603137]])

In [25]:
transform_points(lane_bounds[0],
                 data["raster_from_agent"]) 

NameError: name 'data' is not defined

In [6]:
our_map, start_position, end_position, start_heading, end_heading = extract_map(train_dataset[50], rast)

In [7]:
print(our_map)

[[1. 2. 2. ... 2. 2. 2.]
 [1. 1. 2. ... 2. 2. 0.]
 [1. 1. 2. ... 2. 0. 0.]
 ...
 [2. 2. 1. ... 0. 0. 0.]
 [2. 2. 1. ... 0. 0. 0.]
 [2. 2. 2. ... 0. 0. 0.]]


In [8]:
print(start_position)

[ 56. 112.]


In [9]:
print(end_position)

[190.51799011 112.31768188]


In [10]:
print(start_heading)

[0.]


In [11]:
print(end_heading)

[-0.00290632]


In [12]:
our_map[100:125,0:10]

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [0., 0., 0., 